What is Dropout in PyTorch ?

Dropout in PyTorch is A regularization method where randomly selected neurons are dropped from the neural network to avoid overfitting. And this is done with the help of a dropout layer that manages the neurons to be dropped off by selecting a frequency pattern. Once the model is entered into evaluation mode, the dropout layer is shutdown, and training of the dataset will be started.

## What is Dropout and how does it work?

With Dropout, the training process essentially drops out neurons in a neural network. They are temporarily removed from the network, which can be visualized as follows:

![](assets/2022-02-20-18-20-22.png)

Note that the connections or synapses are removed as well, and hence no data flows through these neurons anymore.

When neurons are dropped, they are not dropped permanently: instead, at every epoch (or even minibatch) the network randomly selects neurons that are dropped only for this time. 

And Neurons that had been dropped before can be activated again during future iterations.

In [1]:
import torch

In [3]:
p = 0.5

layer = torch.nn.Dropout(p)

layer.training

True

In [5]:
input = torch.ones(3, 5)
input

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [6]:
layer(input)

tensor([[2., 2., 2., 2., 2.],
        [2., 0., 0., 2., 0.],
        [2., 0., 2., 0., 2.]])

In [7]:
layer(input)

tensor([[0., 2., 2., 0., 2.],
        [2., 2., 0., 2., 0.],
        [2., 2., 0., 2., 0.]])

In [8]:
layer(input)

tensor([[0., 0., 0., 2., 2.],
        [2., 0., 0., 0., 0.],
        [2., 2., 2., 0., 2.]])

In [11]:
1/(1-p)

2.0

In [12]:
layer.eval()

Dropout(p=0.5, inplace=False)

In [13]:
layer.training

False

In [14]:
layer(input)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [15]:
layer(input)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

And we can see in the evaluation mode the dropout layer behaves exactly like identity mapping.